name: Release SwaggerUI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run automated-release -- --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: PUBLISH_DIST=true bash swagger-ui-dist-package/deploy.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: PUBLISH_FLAVOR_REACT=true bash flavors/swagger-ui-react/release/run.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
